### ISSUE TITLE
Update portuguese translation

### ISSUE THREAD

**Issue by trmurakami** [tematres/TemaTres-Vocabulary-Server#11]
[pt-utf-8.inc.php.txt](https://github.com/tematres/TemaTres-Vocabulary-Server/files/913002/pt-utf-8.inc.php.txt)

File

**Comment by horus68** [comment]
Note: the @trmurakami should be considered not for a "pt" but a for a `pt-BR` translation (Portuguese - Brasil).
I would like to have a proper `pt` language file (or `pt-PT` for Portuguese Portugal). 
@tematres I think that a change in code must be created to allow a 4 letter language code. 
So please use the actual "pt" file to create the pt-PT and the pt-BR. then I will submit a PR with a revised translation for pt-PT

**Comment by horus68** [comment]
@trmurakami Hi tiago,
you should now close this PR and create a new one because there is now a PT-BR language file
I updated the actual pt file that will be for Portuguese (Portugal)
Bom trabalho!

**Comment by horus68** [comment]
This can now be closed. Will submit an updated translation for all languages from Crowdin that also includes this one.
