### ISSUE TITLE
Bug: Exporting a term in DC format does not respect the URL prefix configured in config.tematres.php

### ISSUE THREAD

**Issue by paulwalk** [tematres/TemaTres-Vocabulary-Server#18]
Having specified a different URL prefix in `config.tematres.php`, the various export formats respect this setting with the exception of the 'DC' format which uses the default URL format in <dc:identifier>

**Comment by tematres** [comment]
Hi Paul, thank you about the debug!! :) We fix it and publish the update right now: https://github.com/tematres/TemaTres-Vocabulary-Server/commit/01a3be8784be9e4acbaefeb82274b940ba6ed4cb

Please let me know about any problem :)

**Comment by paulwalk** [comment]
Thanks - very quick fix! :-)
