### ISSUE TITLE
The Termatres API redirects to the login page

### ISSUE THREAD

**Issue by irpye** [tematres/TemaTres-Vocabulary-Server#21]
We want to query the Termatres API from the web interface of another application.

It works correctly if we are logged on Termatres on the same browser. 

But, if we are not logged in, the request on the API fails because it returns to the login page.

Where could this problem come from ?

Thank you.

**Comment by tematres** [comment]
Hi, may be you call the api using rewrite rules (ex: http://www.r020.com.ar/tematres/demo/api/search/french/json or http://www.r020.com.ar/tematres/demo/api/search/french) and you do not enalbe the mod_rewrite in apache. 
Try: http://www.r020.com.ar/tematres/demo/services.php?task=search&arg=french
or http://www.r020.com.ar/tematres/demo/services.php?task=search&arg=french&output=json

Or the web services are disable in the tematres instance . Check the status calling the feed without params: http://www.r020.com.ar/tematres/demo/services.php

OK? please let me know about any problem or doubt (and sorry about my english :/)

**Comment by irpye** [comment]
Hello and thanks for the answer.
The API may be disabled. 
When  i call the feed without params, i am also redirected to the login page.
How do i enable the API ?
(And sorry for my english too).

**Comment by tematres** [comment]
Access to the form configuration: Login as admin: Menu -> Configuration : Click in the title of your vocabulary in the Configuration div.
In the form configuration you can enable the web services. 
Wich language you prefer? (spanish?? :))

Can you share the URL of your vocabulary to check the problem?

best regards
