### ISSUE TITLE
Master language and collaborative online translation [RFC]

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#24]
This is a request for comment/new feature: @tematres
In TemaTres what is the language file to be considered as the "source/master language"? English or Spanish?

This because I would like to setup a collaborative translation platform to translate files online.
Its faster and makes any file fully synchronized with the original.
In any translation software English should be the source for the others but I don't know if the english file from Tematres is fully updated with the spanish as there are some little differences.

### Collaborative online translation
I would like to use a translation platform like Transifex or Crowdin (both free for opensource). I can setup it myself or better yet ask Diego to create it and then allow us to translate.
Note: Those platforms allow language team managers (approval rights) and plain translators for each language, so things will not be deleted by a new member! Actual translators would be invited as team languages managers.
The updated translations could be submitted to GITHUB by each translator or by the Tematres author.
Download from the system is free too (using web interface or using their CLI tools)

**Comment by tematres** [comment]
Hi :) the main language of Tematres is english, buy i'm not fluent in english :( ... so I try to mantain both languages. I try to mantaine the documentation in english in http://vocabularyserver.com/wiki
Bue my english is bad. Please tell me wich aspect of Tematres we need to improve the documentation (with priorities :)).

We can use  collaborative translation platform in order to translate all the tematres family tools :)

In this week we release the 1.0 version or WordPress Plugin :) http://r020.com.ar/wp-tematres-1-0/

best regards! :)

**Comment by horus68** [comment]
@tematres can you create a project for translation using Crowdin https://crowdin.com or Transifex https://www.transifex.com .
You can use whatever platform you prefer (I do prefer Crowdin), I will gladly help you to setup and upload actual translations and source files. I only need you to create the project with the proper master language.
This way you will be the project owner and them you can add me as a project administrator (or change your mind later!)
My user for invitation: https://crowdin.com/profile/horus68 or https://www.transifex.com/user/profile/horus68/

**Comment by horus68** [comment]
@tematres to be able to setup the project you created, you need to make me Manager for the Crowdin project. I sent you a message in Crwodin with details

**Comment by horus68** [comment]
Just an update: 
A project has been created in Crowdin by Diego to test interface translation.
I'm now finishing the setup and uploading translations. In some hours it will be available for collaborative translations. Stay tuned to help on your language!

![tematres-translation1](https://user-images.githubusercontent.com/3055443/45416557-1b96d280-b678-11e8-8b60-f99c39b3944c.png)

**Comment by horus68** [comment]
@japotrad > Hard point #2: Check the user interface (Tematres website) the terms for menus, buttons and other navigation elements. Several times, I had "creative" translations ideas, but then I realized that the same term (text ID) was used in several screen wheareas my own "creative" French translation would be good only in one screen. So, I had to roll back my "creative" stuff.

Can you open a new issue with that request and pointing some examples of strings that require different usage? Then maybe we can get different strings for different interface areas (even if they could have the same value in english).

**Comment by horus68** [comment]
Please join the new project to translate your language. Its free to translate and download.
1- Login/Sign up to Crowdin site https://crowdin.com/
2- Join your TemaTres language in https://crowdin.com/project/tematres

You will be approved as a translator. When joining please send me a message via Crowdin (horus68) on why should you also be a proofreader.
Each language can have translators (suggestions and votes) and Proofreaders (translate + vote + translations approval)
