### ISSUE TITLE
The terms were deleted or not? [Language]

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#26]
There is an issue with a language value in the file: /common/lang/en-utf-8.inc.php
The English versions says "the terms were deleted" but the Spanish version says "the terms were NOT deleted". Some languages translated it from the English and some from the Spanish, ending up with opposite translations.
So I'm requesting @tematres for a clarification on this!

English:
`define('MSG_termsNoDeleted','the terms were deleted');`
https://github.com/tematres/TemaTres-Vocabulary-Server/blob/master/common/lang/en-utf-8.inc.php#L436

Spanish
`define('MSG_termsNoDeleted','términos no fueron eliminados');`
https://github.com/tematres/TemaTres-Vocabulary-Server/blob/master/common/lang/es-utf-8.inc.php#L436

Note: The string was introduced in v2.0, see https://github.com/tematres/TemaTres-Vocabulary-Server/commit/b87fef95c3cf09b6a94f9f97f60a67b45894ee9a#diff-29b0d3bfb89baa1606661df8f76ad8b1

**Comment by tematres** [comment]
ooopsss! The correct label is: "The terms were NOT deleted"

We use this message when the term to delete have relations

thank you!
