### ISSUE TITLE
Importing SKOS

### ISSUE THREAD

**Issue by ncarboni** [tematres/TemaTres-Vocabulary-Server#3]
Hi, 
I am trying to import the FISH Building Materials Thesaurus in TemaTres [1]. After choosing the SKOS-Core option, and clicking import I get the message "Import task finished" but nothing really happens. It seems it works, but it doesn't. Do you have any idea what I am doing wrong?
Thanks !

[1] http://www.heritagedata.org/blog/vocabularies-provided/  http://heritagedata.org/live/seneschal_eh_560_20130717.rdf

**Comment by tematres** [comment]
Hi, I will review the case, buy my first impression is because the Skos-core source file encode for each relation all the term. For example: 
<skos:narrower><skos:Concept ... bla bla

**Comment by mroszkowski** [comment]
Hi everybody,
I got the same problem with skos files. In some cases, everything goes smooth but I often get the response:
"Creating default object from empty value in /.../common/include/inc.importSkos.php on line 345"
Is there a problem with skos file formatting?
I'm trying to import http://data.culture.fr/thesaurus/page/ark:/67717/T69
All the best,
Marcin
