### ISSUE TITLE
Labels missing -Vocab Config

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#35]
There is some language values missing in Vocab config menu
Using version 3 (from Git). It doesn't look to be a problem caused by language file missing keys.

See:
`CFG_PUBLISH`
![2019-05-06 14_07_14-](https://user-images.githubusercontent.com/3055443/57229445-03603300-700e-11e9-8fb0-f279a18c413e.png)

The table:
![2019-05-06 15_06_47-localhost _ mysql wampserver _ indexa11 _ lc_values _ phpMyAdmin 4 1 14](https://user-images.githubusercontent.com/3055443/57230636-b16cdc80-7010-11e9-82c1-af7c461a80a5.png)

**Comment by tematres** [comment]
was solved (by you... i think :))
