### ISSUE TITLE
Incorrect datetime value

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#36]
Working with from an empty database, TemaTres 3.0 (from git repo), Windows wamp server, PHP 7.03, MySQL 5.7.17, with Debug on.

When importing a file (labeled file) an error is displayed when the process ends:
`Incorrect datetime value: '0000-00-00' for column 'cuando_final' at row 1Incorrect datetime value: '0000-00-00' for column 'cuando' at row 1`
The import process concludes fine. Should the error be avoided or is it safe to be ignored?

![2019-05-06 16_18_42-localhost _ mysql wampserver _ indexa11 _ lc_tema _ phpMyAdmin 4 1 14](https://user-images.githubusercontent.com/3055443/57235390-af0f8000-701a-11e9-93d4-76bf2264dbab.png)

![2019-05-06 16_17_18-localhost _ mysql wampserver _ indexa11 _ lc_tema _ phpMyAdmin 4 1 14](https://user-images.githubusercontent.com/3055443/57235344-8edfc100-701a-11e9-9a3b-d30f468190c0.png)

**Comment by tematres** [comment]
Fixed in https://github.com/tematres/TemaTres-Vocabulary-Server/commit/794ee90d0a3f9fb110458aedc22af3f6c0a44a44

Please check :) thank you!
