### ISSUE TITLE
Warning: implode(): Invalid arguments passed - fun.xml.php

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#37]
Just FYI:
```
Warning: implode(): Invalid arguments passed in 
..\common\include\fun.xml.php on line 1013
```
![2019-05-06 19_51_38-INDEXA RBE - Lista geral](https://user-images.githubusercontent.com/3055443/57247851-ce1d0a80-7038-11e9-9441-a67d5ab4e6bb.png)

Setup:
TemaTres 3.0 (from git repo), clean database,
Windows wamp server, 
PHP 5.6.18 (also display if using 7.03), MySQL 5.7.17, with Debug on.

**Comment by tematres** [comment]
thank you! this is a bug. :/ The error happen when there are no data about terms or tops terms. Now is fixed (I hope :)). 
thank you!
