### ISSUE TITLE
Language codes when using TinyMCE

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#38]
Using Tematres 3 with language pt-PT, error from tinymce shows when editing a term note:

`Failed to load plugin url: http://localhost/indexa11/common/tinymce/langs/pt-PT.js`

Folder has the proper language file but its using the name after code with underscore: `pt_PT.js`
When renaming to `pt-PT.js` the error goes away but for the translation to be used had to change the first line of the file for
`tinymce.addI18n('pt-PT'`

Strange: There is also another folder with language files at:
common/tiny_mce4/langs

Tematres sholud also update the tinyMCE from source http://www.tinymce.com/
Translators can improve their language files here https://www.transifex.com/projects/p/tinymce/

**Comment by tematres** [comment]
hi, i cant find pt_PT in https://www.tiny.cloud/get-tiny/language-packages/, we can adopt pt_BR?

**Comment by horus68** [comment]
No! 
Its strange because the file is fully translated (and also used in many other systems like Joomla!)

**Comment by tematres** [comment]
in the last commit the pt_BR and pt_PT was renamed to pt-BR and pt-PT.
