### ISSUE TITLE
Fields not saved - Vocab Config

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#39]
Bug report: there are 3 fields in vocab config not saving data.

![indexa_voc_about](https://user-images.githubusercontent.com/3055443/57302723-bd6da280-70d3-11e9-957a-9895c2f87ac4.png)

**Comment by tematres** [comment]
hi :), we test it and cant reproduce the error. May be this can be problem in the create the default configuration data. Do you can try run the process to update form 1.6 > 2.2 (Menu -> Admin -> Database mantainase) please?

**Comment by horus68** [comment]
Done that now, no success!
(The db is a new one, created by Tematres 3.0 Git version)
I used MySQL 5.7.17 with PHP 5.6.17 in a localhost setup (Wamp server)

**Comment by tematres** [comment]
was solved
