### ISSUE TITLE
Tematres with PHP 7

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#42]
just for a report on PHP compatibility

- Termatres vocab works fine with PHP 7.0.3 and 7.0.11

- Many errors with PHP 7.2.14 (debug on)
![2019-05-07 20_54_01-INDEXA RBE - Tesauro geral - Opera](https://user-images.githubusercontent.com/3055443/57329112-01c86500-710b-11e9-90c5-10cb17b65fea.png)

**Comment by tematres** [comment]
was solved in 3.2
