### ISSUE TITLE
TemaTres is distributing the .git/ directory as part of the release

### ISSUE THREAD

**Issue by marijane** [tematres/TemaTres-Vocabulary-Server#48]
I was quite surprised to unzip tematres3.1.zip today to discover a .git/ directory among the usual tematres files.  (I use [bash-git-prompt](https://github.com/magicmonty/bash-git-prompt), which changes my shell prompt whenever I cd into a git repo.)

I am not sure if there are any particularly good reasons not to do this, but it seems like something one would not want to do.

**Comment by tematres** [comment]
Hi, @marijane thank you about the notice ... I do not want to include .git in the source code, but when I download the source code do not include the ..git/ directory. 
How do you do to get the code? ... and do you can help me to exclude the .git directory from the source  code?  :)

thank you in advance and sorry about my english

**Comment by marijane** [comment]
Hello @tematres, I downloaded it today from https://sourceforge.net/projects/tematres/.  
Note that since .git/ is a hidden directory, you will need to use 'ls -la' to see it in the directory listing at the command prompt. (assuming you are on a Unix-like system.)

Assuming you are using the zip utility to create the file, you would add '-x *.git*' to the end of the command to exclude it.  

Another method would be to use [GitHub's release feature](https://help.github.com/en/github/administering-a-repository/about-releases), which would allow you to distribute releases via GitHub in addition to SourceForge.

**Comment by tematres** [comment]
Thank you again @marijane :) I forgot to delete the directory in sourceforge :/
Now it was removed :) To the next release I will try to use GitHub release feature
Thank you about your help :)
