### ISSUE TITLE
After importing a skos-core file, the front page hierarchy is not displaying in alphabetical order

### ISSUE THREAD

**Issue by marijane** [tematres/TemaTres-Vocabulary-Server#49]
I am trying to move a vocabulary from a TemaTres installation hosted on my work laptop to one hosted on a web server.

**Here is what I did:**
1. Export entire vocabulary from my laptop TemaTres in skos-core format
2. Import skos-core file into the cloud-hosted TemaTres 

**Result:**
The hierarchy on the front page of my taxonomy at my web host is not displaying in alphabetical order.
See it at https://ohsu-library.000webhostapp.com/ohsu-research/index.php

**Expected Result:**
The hierarchy on the front page should be in alphabetical order, just like on my laptop.

**Comment by marijane** [comment]
What might be causing this problem?  How might I fix it?  

The front-page hierarchical display is the primary feature I need for this particular taxonomy and the fact that it's not showing up in order is a big problem.

**Comment by marijane** [comment]
Also, other things I tried that did not work:

1. I first tried to export the SQL backup and I tried to run that in the SQL query interface at my web host.  I got a SQL error about the uid_final value for a particular row being empty.
2. I also tried exporting and importing in MARCXML format.  This failed with no error message.

**Comment by marijane** [comment]
I figured this out!

I realized I might be able to work around this problem by using codes.  Turning on codes is when I discovered that the skos-core export will import a bunch of URIs into the code fields.  I deleted these, and now my front page is sorting alphabetically again.

There may be a logic bug with the "use codes" option.  I did not have it enabled, and yet my front page was still using them for sort order.

**Comment by tematres** [comment]
Hi @marijane :) the code data are optional and is used to assign notation as a unique and arbitral "notation" to each term. If was enable, is used as primary sorting criteria. Is optional and can be public (show in the public interface) or only as sorting criteria (when are configured as USE_CODE=YES + SHOW_CODE=NO) .

In the SKOS-core import process, we use the URI of each term as unique notation asigned to term (to solve a SKOS-core problem emerged because Skos-core is a concept-centric schema and not a term-centric schema)

In your case the USE_CODE is configurated as NO? Do you can try logout to check if maybe is a "session data" problem?

thank you! :)

**Comment by marijane** [comment]
USE_CODE was configured as NO, and I did try it from a different browser, the problem persisted.
I deleted all the codes, so at the moment I can't test to see if it's a session data problem, but I have a couple other vocabularies I'll be moving over to my web host, so there's a chance I will hit this again.

**Comment by tematres** [comment]
hi @marijane  :) i go to review this in order to try to reproduce it in local environment.

**Comment by tematres** [comment]
if you need import a vocab from local to web environment and do yo cant import form SQL, may be the best way is export alphabetic.txt and import from "tagged text" source file.

**Comment by marijane** [comment]
That's good to know, I didn't realize the alphabetic text export could be imported as tagged text.
