### ISSUE TITLE
Lang file names for en-GB and en-US

### ISSUE THREAD

**Issue by sparkji** [tematres/TemaTres-Vocabulary-Server#50]
Lang files for en-GB and en-US has been changed, but files in common/tinymce/langs were not updated.
en_GB.js should be renamed to en-GB.js, en-US does not exist in the folder.

Failed to load plugin url: http://.../common/tinymce/langs/en-GB.js
Failed to load plugin url: http://.../common/tinymce/langs/en-US.js

**Comment by tematres** [comment]
ooopss: / It's true :( I'm sorry. We just added the files (en-GB and en-US). Thank you! :)

**Comment by horus68** [comment]
@tematres now you have both 
```
en-GB.js
en_GB.js
```
Other languages also having different file names
https://github.com/tematres/TemaTres-Vocabulary-Server/tree/master/common/tinymce/langs

**Comment by horus68** [comment]
@tematres can you please reopen this or take a second look into it?
In git you have both file names
