### ISSUE TITLE
Can't see the A-Z menu when logged in

### ISSUE THREAD

**Issue by marijane** [tematres/TemaTres-Vocabulary-Server#51]
I have set up a vocabulary at http://taxo.space/ohsu-dam/index.php
It currently only contains candidate terms.

The A-Z menu is not visible after I log in.  I can see it fine when I'm logged out.

This seems like a bug.  If anything, I would expect it to work the other way around.

**Comment by tematres** [comment]
HI @marijane is very strange :( I will to try to reproduce the problem. Can you try to include 1 accepted term (to test the instance).
If you want you can config your vocab to avoid public view (Admin -> Configuration)

**Comment by marijane** [comment]
Hello @tematres I have added three meta-terms, and now the letters that contain those terms are showing up when logged in, but the rest of the alphabet is still missing.
I am going to look at some of my other instances to see if I'm seeing the same behavior there.
Thank you for the reminder about public view -- I do in fact want this vocabulary to be private, at least for now.

**Comment by tematres** [comment]
Hi Marijane :) we can't reproduce the behavior :/ If you agree we can create one instance in our public ssandbox and you can try to reproduce the bug and we try to fix it.
By the way, Tematres only show letters in alphabet menu if there are terms begginings with this character. 

I see you have other vocabs, may be this tools can be useful  for your project:
PortalThes demo: https://vocabularyserver.com/portalthes/
PopTerms demo :https://vocabularyserver.com/popterms/client-example/

The code are availve here :)

Cheers and thank you for the feedback
(diego)

**Comment by marijane** [comment]
> By the way, Tematres only show letters in alphabet menu if there are terms begginings with this character.

Yes, understood.  My instance has over 3200 terms in it, but I created them all as candidate terms, and apparently TemaTres won't show the letters if terms are only candidates.  For example, I have 213 candidate terms that start with the letter A, but the letter A doesn't appear in the alphabet menu, despite being able to see the entire list if I manually enter the page address http://taxo.space/ohsu-dam/index.php?letra=A.  I can understand not showing the A in the alphabet menu for a public view if the terms are only candidates, but I would expect to be able to see them when logged in.

I created my own debugging instance and I have precise reproduction steps now:

1. Create a new empty TemaTres instance
2. Log in
3. Click **Add Term**
4. Enter a list of terms
5. Check the **Candidate term** box
6. Click the **Submit** button
7. Click **Home**

**Result:**

- The Home screen is empty.  There is no alphabet menu.
- If you log out, the alphabet menu is visible, but the pages are empty.

**Expected Result:**

- When logged in, the alphabet menu should be visible for the letters that have candidate terms that begin with those letters.
- When logged out, the alphabet menu should not be visible because all of the terms in the vocabulary are candidate terms.

My debugging instance is at http://taxo.space/debug/index.php.
I am running the most recent version of TemaTres on PHP 5.6.

**Comment by tematres** [comment]
Hi Marijane, thank you about detailed documentation! :) we achieve to reproduce the problem and fix it. Please update your code (common/include/fun.sql.php) 

Please let me know if it's ok.

best

**Comment by marijane** [comment]
Excellent!  I have updated the file on my server and I can confirm that it's now working as expected.  I will close this issue.
