### ISSUE TITLE
Language typos was reverted by mistake?

### ISSUE THREAD

**Issue by horus68** [tematres/TemaTres-Vocabulary-Server#55]
issues #47 and #46 with language typo fixes (already merged) was reverted in the language files by mistake?

See commit https://github.com/tematres/TemaTres-Vocabulary-Server/commit/7b0c1492948ca0cbf9308df6e54a3a12c41b8aab

**Comment by tematres** [comment]
Hi Andreas, I do some (a lot) mess with git :((( Can you tell me or send references to (re-)fix the mistakes in typos?
Tahnk you and sorry :/

**Comment by tematres** [comment]
Can I download the fixed version from https://crowdin.com/project/tematres/ ?

**Comment by horus68** [comment]
Crowdin updated now for typos in english and some other languages

Note: you now have 2 different files for each language, as in
es-ES-utf-8.inc.php
es-utf-8.inc.php

**Comment by tematres** [comment]
thank you :+1:
