### ISSUE TITLE
Feature Request - MARC 21 XML Import - Additional Elements

### ISSUE THREAD

**Issue by clifforddavy** [tematres/TemaTres-Vocabulary-Server#59]
Hello,

As far as I can tell, "Import thesaurus from file" using the format "MARC 21 XML" will import the following Topical Term elements: 

-  Term
-  BT
-  NT
-  UF
- USE (?)

That is; MARC tags 150 and 550 (subfield w).

If it does import other elements, I cannot find them; please let me know if I am doing something wrong, and just missing them.

If it is correct that other elements are not being imported, can some more be added please?

It would, for example, be very beneficial to include "Field Definition and Scope" with the MARC XML import.  
That comes under MARC 68X  (See: [https://www.loc.gov/marc/authority/ad66768x.html](https://www.loc.gov/marc/authority/ad66768x.html)). 
Here is a sample:

	<datafield tag="150" ind1=" " ind2="0">
	<subfield code="a">Firedamp</marcxml:subfield>
	</datafield>
	[...]
	<datafield tag="680" ind1=" " ind2=" ">
	<subfield code="i">
	Here are entered works on methane as a combustible gas formed in coal mines. Works on methane present in a stratum of coal are entered under
	</subfield>
	<subfield code="a">Coalbed methane.</subfield>
	</datafield>
	<datafield tag="681" ind1=" " ind2=" ">
	<subfield code="i">Note under</subfield>
	<subfield code="a">Coalbed methane</subfield>
	</datafield>

(Derived from: [https://id.loc.gov/authorities/subjects/sh85048469.marcxml.xml](https://id.loc.gov/authorities/subjects/sh85048469.marcxml.xml))

With thanks,
Clifford.

**Comment by tematres** [comment]
Hi Clifford! sorry for the delay in response (and please be patient with my english). Actually the import procedure from MARC21-XML does not include any notes tag, but this is a great idea :)!

We can include :
677 as definition note
678 as bibliographic note
680 as scope note
681 as example note
688 cataloging or history note (¿wich?)

Do you agree?

thank you about your feedback :)

**Comment by clifforddavy** [comment]
Dear Diego,

Thanks for your response.
Your suggestions are excellent.
It would be very beneficial if these could be added.
Might be useful to include 670, "Source Data Found", too, if possible; but not if that introduces complications for you(?).
Thank you very much.

Regards,
Clifford.

**Comment by tematres** [comment]
Hi Clifford, there is no problem to include 670. Do we map this tag to bibliographic notes?

regards :)

**Comment by clifforddavy** [comment]
Dear Diego,

Thank you.

Before I get to 670, your question prompted me to look at your list of mappings again.

> 678 as bibliographic note

In MARC, 678 is [Biographical or Historical Data](https://www.loc.gov/marc/authority/ad678.html). So, under the note types available in TemaTres, I wonder if "Historical note" might not be more appropriate?
Sorry I didn't pick that one before.
What do you think?


> 670. Do we map this tag to bibliographic notes?

MARC "Source Data Found" may be bibliographic, but in some cases it might be something else.
Never-the-less, with the available note types, I think, yes, your suggestion is the best option.

> 688 cataloging or history note (¿wich?)

My apologies for not responding to this query earlier.
If 678 is to be used for "Historical note", I think it better to keep that and 688 ([MARC Application History Note]( https://www.loc.gov/marc/authority/ad688.html)) distinct.  So, I would suggest "Cataloguing note" for this.

How does that all sound to you?  I am open to other suggestions.

Many thanks for your time and effort on this.

Regards,
Clifford.

**Comment by tematres** [comment]
hi Clifford, sorry about the delay :/ now the notes are included in the import procedure from MARC21- XML. In order to maintain uniform criteria, we  only include the subtag $a. is that really bad?

please test it. :) thanks you
