### ISSUE TITLE
Terms with no subordinates are not displayed in tree

### ISSUE THREAD

**Issue by olufine** [tematres/TemaTres-Vocabulary-Server#60]
I have a hierarchical vocabulary in which some of the terms have no relationship to any other terms. 
With parameter _SHOW_TREE=Yes, the unrelated terms do not show up in the hierarchy on the Home page. For all intents and purposes unrelated terms are top terms, and should as such be displayed in the hierarchy up front. 
As it is now, only top terms with subordinates are shown. Is there something we can do to correct this?

**Comment by tematres** [comment]
hi @olufine In Tematres displays as top terms are any term who have narrower terms and do not have broader terms. ¿In wich case one term can be a top term if the term do not have any narrower terms?

**Comment by olufine** [comment]
In cases where we don't want to subdivide the term, or just haven't done it yet. I would argue that the only requirement for being a top term should be that it has no broader terms (in the same vocabulary). SKOS doesn't even require that much, but recommends it as a convention (see https://www.w3.org/TR/2009/NOTE-skos-primer-20090818/ ch 2.5).
The vocabulary in question is a somewhat uneven (in terms of hierarchy depths) vocabulary of musical genres, with about 600 terms.  About 110 are at top level, but only 19 of these are further subdivided. Hence there are about 90 terms with no BT nor NT, which I would like to appear in the hierarchical view as top terms. 
Moreover, I  also notice that those terms are not exported as top concepts in the SKOS export, which they should have been
