### ISSUE TITLE
Adding a language

### ISSUE THREAD

**Issue by pvperez1** [tematres/TemaTres-Vocabulary-Server#72]
Hi, thank you for this software, I am a new user.

We are creating a multilingual thesaurus in the different Philippine languages. However, when adding a scope note to a term, in the Language dropdown, we do not have the languages we are using (which is what we expected). How can we add languages in the dropdown?
<img width="548" alt="Screenshot 2022-04-22 010359" src="https://user-images.githubusercontent.com/29356154/164514205-4c02aa78-33de-4537-b7e4-0e2336bb6753.png">

I checked the wiki and was also looking for user manuals in English but I may have missed them, if this is already addressed in those, I would appreciate anyone pointing me in that direction. Thanks again!

**Comment by tematres** [comment]
Hi @pvperez1 we just right now added en-PH (English of the Philippines) and tl-PH (Tagalog) to the list of enable languages. The list can be configured in common/include/config.tematres.php (to add the language to all the tematres instances) or in vocab/config.tematres.php to add only to specific instance.
Sorry about our lack documentation in english, and sorry about my  english ://

best regards and thank you about any feedback :)

**Comment by pvperez1** [comment]
Thank you for letting me know where the list can be configured, we need that as we will be adding more local Filipino languages that are not well known. You're English is great, and thanks again for maintaining this software! :)

**Comment by tematres** [comment]
Hi @pvperez1 which is the 5 letters iso code for Filipino language? ph-PH ?

thank you :)

**Comment by pvperez1** [comment]
Hello, from what I understand, there is no 639-1 for Filipino, only a 639-2 (fil). This will also be the case for the other Philippine languages that we will be using, all only having the 3-letter 639-2 code. How can we add these?

**Comment by horus68** [comment]
To translate online please use https://crowdin.com/project/tematres
Code FIL added. No other filipino available on Crowdin do be added
