### ISSUE TITLE
How to import Skos-Core file to TemaTres?

### ISSUE THREAD

**Issue by chenkun19960427** [tematres/TemaTres-Vocabulary-Server#75]
Hi,

How to import Skos-Core file to TemaTres?

I read the description on the [TemaTres's official website](https://vocabularyserver.com/web/manage) (```Import from Skos-Core, tabulated or tagged text file```). But I couldn't find some documents about ```Import from Skos-Core```.

Is there some documents to `import Skos-Core files`?

Best Regards

**Comment by tematres** [comment]
Hi @chenkun19960427 :) To import file into your Tematres follow this stpes:
1. Login as admin
2. Menu -> Administration -> Import
3. Select Skos-core

Please, let me know about any problem or doubt :)


best regards
