### ISSUE TITLE
Reports based on modification date

### ISSUE THREAD

**Issue by olufine** [tematres/TemaTres-Vocabulary-Server#78]
Currently, it is possible to filter **reports** and **Advanced search** according to the creation month of the terms ("Created on or after"). It would be great if the same could be offered for modification. That is, we would like to be able to take out reports on terms "Modified on or after".

**Comment by olufine** [comment]
That's nice - thank you very much!. But the code version is still presented as v. 3.3., released in Dec 2021 (long before the mentioned change), hence the latest change does not seem to be reflected in the version history,. Shouldn't that be in order also, before anyone tries to install it?

**Comment by olufine** [comment]
Hi again,  I've just consulted with my local IT department, and they are unwilling to install the update before it is served out in a new release.  I would be grateful if you could do that. So far, it seems you've just pushed the update onto the master branch...

**Comment by tematres** [comment]
Hi again me too :). Today we release the 3.4 version of tematres!: https://github.com/tematres/TemaTres-Vocabulary-Server/releases/tag/v3.4

Please let me know about any problem, doubt or suggestion :)

best regards and thank you!
