### ISSUE TITLE
Password recovery sent multiple new passwords

### ISSUE THREAD

**Issue by ligiadf** [tematres/TemaTres-Vocabulary-Server#83]
I have a fresh install of Tematres and I think I found a bug: I requested a new password but received 3 new ones in 8 hours.

URL: /vocab/login.php?task=recovery

Details:
- I received a new password right after requesting it, I changed it to a new one and continued using Tematres (that's the expected).
- After like 5,5 hours I received another new password in the email.
- After another 2 hours I received another one.

These 3 messages were all with different passwords and I received them duplicated (2 emails at each time).

![image](https://github.com/tematres/TemaTres-Vocabulary-Server/assets/39387852/4ecf3c01-0ec9-43e2-aab1-b0598959188d)

**Comment by tematres** [comment]
Thank you @ligiadf !! we fix this bug in https://github.com/tematres/TemaTres-Vocabulary-Server/commit/795649daffa8a2e2d80b69dbc08ef9a60a4a35ad

Thank you! :)
