### ISSUE TITLE
When a user resets his Emailaddress or Password the user account data gets lost/ deleted

### ISSUE THREAD

**Issue by MDemir81** [tematres/TemaTres-Vocabulary-Server#90]
Hi,

we currently have the following problem:
An Admin create an account for a new user with role editor, sets up name, email address etc.
The new user logs in and tries to reset the email address or password of the new account and this leads to the following problem:
1. The user name + surename get deleted.
2 .The email address somehow gets deleted or changes to some other email address (from browser cache?).
3. The user can not login anymore because of the issue mentioned at 2.
(4. Maybe password also gets lost or changed, but I did not test it.)

<img width="362" alt="resetting own password_1" src="https://github.com/tematres/TemaTres-Vocabulary-Server/assets/107849873/17d7a062-944f-4bb9-9034-2453365ea8dd">
<img width="342" alt="resetting own password_2" src="https://github.com/tematres/TemaTres-Vocabulary-Server/assets/107849873/cfa5f46e-7b6d-45f4-849a-238f1e86b767">
<img width="403" alt="resetting own password_3" src="https://github.com/tematres/TemaTres-Vocabulary-Server/assets/107849873/1316ac40-56f7-4ac5-b369-9e860dcddec4">

The user has no possibility to recover or fix his account so an admin has to reset the data but when the user changes the password or emailaddress most of the time this error appears. We have one user who still ist waiting for his access. I think it is not an option that he stays with the password an Admin has generated for the editor.

Unfortunately we could not find any issues in the log even with debug mode set to 1.

We are using TemTres Version: 3.4.1
Browsers: Google Chrome Version 85.0.4183.121 (Official Build) (64-Bit) or Firefox 124.0.2 (64-Bit)

My kind regards
Ali

**Comment by tematres** [comment]
Hi Ali, in the old version of tematres we have some bugs, especially if you use PHP 7x or 8x.
Can you update your version to the latest stable (3.4.4) ? Or the 3.5 (candidate)?

**Comment by MDemir81** [comment]
Thank you Diego, you are right, this makes the most sense.

**Comment by MDemir81** [comment]
It seems the issue is solved with TemaTres 3.4.4.
