### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by olufine** [tematres/TemaTres-Vocabulary-Server#91]
Hi, Recently,  we have struggled with extremely poor performance in TemaTres, with 5-10 secs response time on link activations in the UX. Our IT person found that TemaTres still supports IE9 and removed that by commenting out rows 2043 and 2053 in the function HTMLheader in fun.html.php. This seems to have solved the problem. Is this a change you'd consider for the next release? After all, IE9 has not been around for some years now.

**Comment by tematres** [comment]
Hi @olufine !! thank you!! You are right! we remove this line in our last commit! :) thanks to you and to the IT team! :)
